<a href="https://colab.research.google.com/github/Wolfang-Perez/curso-programacion-cientifica/blob/main/ejercicios/taller_evaluativo_01_calidad_del_aire.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Taller Evaluativo 01 — Calidad del Aire (PM2.5)

**Estudiante:** Wolfang Felipe Pérez Roldán  
**Fecha:** 13 de septiembre de 2026

## Ejercicio 1 — Ficha de la campaña de medición

Se guardan los datos de la estación en variables, cada una con el tipo que
le corresponde: texto (str), enteros (int), decimal (float) y verdadero/falso
(bool).

Al final se revisa el tipo de cada variable con `type()`.

In [1]:
codigo_estacion = "EST-01"
sector = "Norte"
altitud_m = 1495
numero_lecturas = 305
latitud = 6.28
sensor_calibrado = True
factor_conversion = 1000

print("codigo_estacion   ->", type(codigo_estacion))
print("sector            ->", type(sector))
print("altitud_m         ->", type(altitud_m))
print("numero_lecturas   ->", type(numero_lecturas))
print("latitud           ->", type(latitud))
print("sensor_calibrado  ->", type(sensor_calibrado))
print("factor_conversion ->", type(factor_conversion))

codigo_estacion   -> <class 'str'>
sector            -> <class 'str'>
altitud_m         -> <class 'int'>
numero_lecturas   -> <class 'int'>
latitud           -> <class 'float'>
sensor_calibrado  -> <class 'bool'>
factor_conversion -> <class 'int'>


## Ejercicio 2 — Conversión de unidades y error

El sensor mide en mg/m3 y hay que pasarlo a ug/m3 multiplicando por 1000
(el `factor_conversion` del Ejercicio 1).

Con la lectura ya convertida se calculan tres errores frente al valor del
patrón: error absoluto, error relativo en porcentaje y error al cuadrado.

In [2]:
lectura_sensor_mg = 0.0418
valor_patron_ug = 40.0

lectura_sensor_ug = lectura_sensor_mg * factor_conversion

error_absoluto = lectura_sensor_ug - valor_patron_ug
error_relativo_porcentual = (error_absoluto / valor_patron_ug) * 100
error_cuadratico = error_absoluto ** 2

print("Lectura del sensor (ug/m3):", lectura_sensor_ug)
print("Error absoluto (ug/m3):", error_absoluto)
print("Error relativo porcentual (%):", error_relativo_porcentual)
print("Error cuadratico:", error_cuadratico)

Lectura del sensor (ug/m3): 41.8
Error absoluto (ug/m3): 1.7999999999999972
Error relativo porcentual (%): 4.499999999999993
Error cuadratico: 3.2399999999999896


## Ejercicio 3 — Cobertura temporal

La estación toma 12 lecturas por hora. Con las 305 lecturas se calcula
cuántas horas y cuántos días cubre el lote.

Solo se usan `//` (división entera) y `%` (módulo).

In [3]:
lecturas_por_hora = 12

horas_completas = numero_lecturas // lecturas_por_hora
lecturas_sobrantes = numero_lecturas % lecturas_por_hora

dias_completos = horas_completas // 24
horas_sobrantes = horas_completas % 24

print("Horas completas:", horas_completas)
print("Lecturas sobrantes:", lecturas_sobrantes)
print("Dias completos:", dias_completos)
print("Horas sobrantes:", horas_sobrantes)

Horas completas: 25
Lecturas sobrantes: 5
Dias completos: 1
Horas sobrantes: 1


## Ejercicio 4 — Validar una lectura

Se revisa si la lectura 41.8 sirve o no. Una lectura sirve si no es el
centinela -999.0 y si está dentro del rango de 0 a 500.

Se calculan tres booleanos y se muestran con `print()`. Aquí no se usa `if`.

In [4]:
lectura = 41.8
codigo_dato_faltante = -999.0
limite_superior_sensor = 500.0

es_dato_faltante = lectura == codigo_dato_faltante

esta_en_rango = lectura >= 0 and lectura <= limite_superior_sensor

lectura_valida = esta_en_rango and not es_dato_faltante

print("Es dato faltante:", es_dato_faltante)
print("Esta en rango:", esta_en_rango)
print("Lectura valida:", lectura_valida)

Es dato faltante: False
Esta en rango: True
Lectura valida: True


## Ejercicio 5 — Clasificar la lectura

Con la lectura del Ejercicio 4 (41.8) se busca su categoría en la escala:

- Buena: hasta 12.0
- Moderada: hasta 35.4
- Dañina para grupos sensibles: hasta 55.4
- Dañina para la salud: más de 55.4

Se usa un `if / elif / else` y se muestra la categoría con `print()`.

In [5]:
if not lectura_valida:
    categoria = "Dato no valido"
elif lectura <= 12.0:
    categoria = "Buena"
elif lectura <= 35.4:
    categoria = "Moderada"
elif lectura <= 55.4:
    categoria = "Dañina para grupos sensibles"
else:
    categoria = "Dañina para la salud"

print("Categoria:", categoria)

Categoria: Dañina para grupos sensibles


## Ejercicio 6 — Limpiar la serie horaria

La lista tiene 12 lecturas, pero dos son -999.0 (dato faltante) y hay que
sacarlas.

Se recorre la lista con un `for`. Cuando aparece un -999.0 se cuenta como
descartado y se usa `continue` para saltarlo. Las demás se guardan en
`lecturas_validas` y se van sumando.

Al final se calcula el promedio y se muestra cuántas válidas quedaron,
cuántas se descartaron y el promedio.

In [6]:
lecturas_pm25 = [8.4, 12.7, -999.0, 15.2, 41.8, 9.6, -999.0, 58.3, 22.0, 13.9, 7.5, 36.1]

lecturas_validas = []
suma_pm25 = 0.0
lecturas_descartadas = 0

for lectura_actual in lecturas_pm25:
    if lectura_actual == -999.0:
        lecturas_descartadas += 1
        continue
    lecturas_validas.append(lectura_actual)
    suma_pm25 += lectura_actual

promedio_pm25 = suma_pm25 / len(lecturas_validas)

print("Lecturas validas:", len(lecturas_validas))
print("Lecturas descartadas:", lecturas_descartadas)
print("Promedio PM2.5:", promedio_pm25)

Lecturas validas: 10
Lecturas descartadas: 2
Promedio PM2.5: 22.55


## Ejercicio 7 — Estadística de la serie limpia

Con las lecturas válidas y el promedio del Ejercicio 6 se calcula el máximo,
el mínimo, el rango y la desviación estándar.

Se usan dos `for`: uno para el máximo y el mínimo, y otro para la desviación
(que necesita el promedio ya calculado).

In [7]:
maximo_pm25 = lecturas_validas[0]
minimo_pm25 = lecturas_validas[0]

for valor in lecturas_validas:
    if valor > maximo_pm25:
        maximo_pm25 = valor
    if valor < minimo_pm25:
        minimo_pm25 = valor

rango = maximo_pm25 - minimo_pm25

suma_desviaciones = 0.0

for valor in lecturas_validas:
    suma_desviaciones += (valor - promedio_pm25) ** 2

desviacion_estandar = (suma_desviaciones / len(lecturas_validas)) ** 0.5

print("Maximo PM2.5:", maximo_pm25)
print("Minimo PM2.5:", minimo_pm25)
print("Rango PM2.5:", rango)
print("Desviacion estandar:", desviacion_estandar)

Maximo PM2.5: 58.3
Minimo PM2.5: 7.5
Rango PM2.5: 50.8
Desviacion estandar: 16.287495203376114


## Ejercicio 8 — Decaimiento tras cerrar la fuente

Después del pico (58.3), la concentración baja 15% cada hora (se multiplica
por 0.85). Se quiere saber cuántas horas pasan hasta llegar a 12.0 o menos.

Como no se sabe cuántas horas son, se usa un `while`. Dentro del while se
actualiza la concentración para que el bucle termine.

In [8]:
concentracion = 58.3
factor_decaimiento = 0.85
umbral_buena = 12.0

horas_transcurridas = 0

while concentracion > umbral_buena:
    concentracion = concentracion * factor_decaimiento
    horas_transcurridas += 1

print("Horas transcurridas:", horas_transcurridas)
print("Concentracion final:", concentracion)

Horas transcurridas: 10
Concentracion final: 11.477777773064126


## Ejercicio 9 — Registros de varias estaciones

Hay tres estaciones, cada una en un diccionario con código, sector,
coordenadas (tupla) y lecturas. Solo EST-03 tiene humedad.

Se recorre la lista con un `for`. En cada estación se saca la latitud y la
longitud, se calcula el promedio con otro `for`, y se saca la humedad con
`get` (para que las que no la tienen no den error).

Al final se clasifica el promedio y se imprime una línea por estación.

In [9]:
registros_estaciones = [
    {"codigo": "EST-01", "sector": "Norte",  "coordenadas": (6.28, -75.57), "lecturas": [8.4, 12.7, 15.2]},
    {"codigo": "EST-02", "sector": "Centro", "coordenadas": (6.24, -75.58), "lecturas": [41.8, 58.3, 36.1]},
    {"codigo": "EST-03", "sector": "Sur",    "coordenadas": (6.19, -75.59), "lecturas": [9.6, 13.9, 7.5], "humedad_relativa": 68.0},
]

for estacion in registros_estaciones:
    latitud_est = estacion["coordenadas"][0]
    longitud_est = estacion["coordenadas"][1]

    suma_estacion = 0.0
    for valor in estacion["lecturas"]:
        suma_estacion += valor
    promedio_estacion = suma_estacion / len(estacion["lecturas"])

    humedad = estacion.get("humedad_relativa", "no disponible")

    if promedio_estacion <= 12.0:
        categoria_estacion = "Buena"
    elif promedio_estacion <= 35.4:
        categoria_estacion = "Moderada"
    elif promedio_estacion <= 55.4:
        categoria_estacion = "Dañina para grupos sensibles"
    else:
        categoria_estacion = "Dañina para la salud"

    print(estacion["codigo"], "|", estacion["sector"], "|", latitud_est, "|", longitud_est,
          "|", promedio_estacion, "|", categoria_estacion, "|", humedad)

EST-01 | Norte | 6.28 | -75.57 | 12.1 | Moderada | no disponible
EST-02 | Centro | 6.24 | -75.58 | 45.4 | Dañina para grupos sensibles | no disponible
EST-03 | Sur | 6.19 | -75.59 | 10.333333333333334 | Buena | 68.0


In [10]:
# Celda de verificación — ejecútela al final, después de todo lo demás
assert type(codigo_estacion) == str, "codigo_estacion debería ser str"
assert type(altitud_m) == int, "altitud_m debería ser int"
assert type(latitud) == float, "latitud debería ser float"
assert type(sensor_calibrado) == bool, "sensor_calibrado debería ser bool"
assert lectura_valida == True, "la lectura del Ejercicio 4 sí es válida"
assert len(lecturas_validas) == 10, "deberían quedar 10 lecturas válidas"
assert lecturas_descartadas == 2, "deberían descartarse 2 centinelas"
assert abs(promedio_pm25 - 22.55) < 0.01, "revise el promedio del Ejercicio 6"
assert maximo_pm25 == 58.3 and minimo_pm25 == 7.5, "revise los extremos"
print("Verificación completada sin errores.")

Verificación completada sin errores.
